name: Run Jest Tests

on: push
    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Install npm dependencies
      run: npm install

    - name: Run Jest Test
      run: npx jest update.spec.ts